services:
  # Prometheus server to scrape metrics
  prometheus:
    build:
      context: ./prometheus
    ports:
      - "9101:9101"
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml.template:/etc/prometheus/prometheus.yml.template:ro
    networks:
      - internal
    environment:
      - NODE_EXPORTER_CLIENTS=${NODE_EXPORTER_CLIENTS}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Node Exporter to collect host metrics
  node_exporter:
    image: prom/node-exporter:latest
    networks:
      - internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  loki:
    image: grafana/loki:2.8.2
    command: -config.file=/etc/loki/config/loki-config.yml
    ports:
      - "3100:3100"  # Expose Loki port for agent instances to push logs
    volumes:
      - ./loki-config.yml:/etc/loki/config/loki-config.yml:ro
      - loki_data:/loki
    restart: unless-stopped
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  promtail:
    image: grafana/promtail:2.8.2
    command: -config.file=/etc/promtail/config/promtail-config.yml
    volumes:
      - ./promtail-config.yml:/etc/promtail/config/promtail-config.yml:ro
      - /var/log/caddy:/var/log/caddy:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - promtail_positions:/tmp
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  grafana:
    image: grafana/grafana:9.5.5
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Default password, will be prompted to change
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
      - GF_SERVER_ROOT_URL=https://logs.${DOMAIN_ROOT}:8443
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  grafana_reverse_proxy:
    image: caddy:2
    ports:
      - "8443:443"  # Access subdomain set in Caddyfile with port 8443 (using internal TLS)
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN_ROOT=${DOMAIN_ROOT}
      - EMAIL=${EMAIL}
    depends_on:
      - grafana
    restart: unless-stopped
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  loki_data:
  grafana_data:
  promtail_positions:
  caddy_data:
  caddy_config:

networks:
  internal:
    driver: bridge
