target: all  # crucial for single-process mode

server:
  http_listen_port: 3100
  http_listen_address: 0.0.0.0  # listen on all interfaces
  log_level: info
  http_server_read_timeout: 300s
  http_server_write_timeout: 300s
  grpc_server_max_recv_msg_size: 67108864
  grpc_server_max_send_msg_size: 67108864

common:
  path_prefix: /loki
  replication_factor: 1

distributor:
  ring:
    kvstore:
      store: memberlist

ingester:
  # Optional Write-Ahead Log (WAL)
  wal:
    enabled: true
    dir: /loki/wal
  lifecycler:
    ring:
      kvstore:
        store: memberlist
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_retain_period: 30s

querier:
  engine:
    max_look_back_period: 168h

query_range:
  cache_results: true

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 50
  delete_request_store: filesystem
  delete_request_cancel_period: 24h

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 30d
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 6
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 5MB
  allow_structured_metadata: true

schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

# Single-node "ring" with no external cluster
memberlist:
  join_members: []
