server:
  http_listen_port: 3100
  log_level: info

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  wal:
    enabled: true
    dir: /loki/wal  # <--- subdirectory of /loki

querier:
  engine:
    max_look_back_period: 168h

query_range:
  cache_results: true

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    shared_store: filesystem
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

compactor:
  shared_store: filesystem
  working_directory: /loki/compactor  # <--- also inside /loki
  compaction_interval: 5m
  retention_enabled: false
