server:
  http_listen_port: 3100
  log_level: info

distributor:
  ring:
    kvstore:
      store: memberlist   # <--- Instead of consul
  replication_factor: 1  # <--- only 1 replica needed

ingester:
  replication_factor: 1  # <--- only 1 replica needed
  wal:
    enabled: true
    dir: /loki/wal  # <--- subdirectory of /loki
  lifecycler:
    ring:
      kvstore:
        store: memberlist # <--- Instead of consul
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_retain_period: 30s
  max_transfer_retries: 0

querier:
  engine:
    max_look_back_period: 168h

query_range:
  cache_results: true

# If you don't need the compactor, you can disable it
# or point it to a local filesystem directory:
compactor:
  shared_store: filesystem
  working_directory: /loki/compactor
  retention_enabled: false
  compaction_interval: 5m

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    shared_store: filesystem
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

# Memberlist config for single-node or small clusters (no consul or etcd needed)
memberlist:
  join_members: []
