target: all  # crucial for single-process mode

server:
  http_listen_port: 3100
  http_listen_address: 0.0.0.0  # listen on all interfaces
  log_level: info

common:
  path_prefix: /loki
  replication_factor: 1

distributor:
  ring:
    kvstore:
      store: memberlist

ingester:
  # Optional Write-Ahead Log (WAL)
  wal:
    enabled: true
    dir: /loki/wal
  lifecycler:
    ring:
      kvstore:
        store: memberlist
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_retain_period: 30s
  max_transfer_retries: 0

querier:
  engine:
    max_look_back_period: 168h

query_range:
  cache_results: true

compactor:
  shared_store: filesystem
  working_directory: /loki/compactor
  compaction_interval: 5m
  retention_enabled: false

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    shared_store: filesystem
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

# Single-node "ring" with no external cluster
memberlist:
  join_members: []
