server:
  http_listen_port: 3100
  log_level: info

# The distributor will route log writes to ingesters. We set min_ingesters=1 so it doesn't expect 2.
distributor:
  shard_by_all_labels: false   # recommended for single-node
  pool:
    min_ingesters: 1           # <--- Key to avoiding "2 live replicas required"
  ring:
    kvstore:
      store: inmemory

# The ingester actually stores log chunks and can use a WAL if desired.
ingester:
  wal:
    enabled: false
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_retain_period: 30s
  max_transfer_retries: 0
  lifecycler:
    join_after: 0s
    observe_period: 0s
    final_sleep: 0s
    ring:
      kvstore:
        store: inmemory

# Where queries are executed
querier:
  engine:
    max_look_back_period: 168h  # 7 days

# For range queries
query_range:
  cache_results: true

# If you don't need the compactor or retention, you can set these to minimal defaults
compactor:
  shared_store: filesystem
  working_directory: /loki/compactor
  compaction_interval: 0s
  retention_enabled: false

# Important limits, including ingestion rate if needed
limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  # Adjust more advanced limits here if desired

# The schema and store config for boltdb-shipper + filesystem
schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    shared_store: filesystem
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

# We are a single-node ring, so no need to join any peers
memberlist:
  join_members: []
