server:
  http_listen_port: 3100
  log_level: info

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_retain_period: 30s
  max_transfer_retries: 0

querier:
  query_store_after: 24h
  engine:
    max_look_back_period: 168h  # 7 days

query_range:
  cache_results: true

store:
  store: filesystem
  filesystem:
    directory: /loki

limits_config:
  max_cache_freshness_per_query: 10m
  reject_old_samples: true
  reject_old_samples_max_age: 168h

schema_config:
  configs:
    - from: 2022-01-01
      store: filesystem
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h