global:
  scrape_interval: 15s

scrape_configs:
  # Scrape the internal node_exporter container
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
  # - job_name: "cadvisor"
  #   static_configs:
  #     - targets: ["cadvisor:8080"]

  # Scrape external node_exporters specified via environment variable
  # The NODE_EXPORTER_CLIENT environment variable is passed in via docker-compose
  - job_name: "node_exporter_external"
    static_configs:
      - targets: ["${NODE_EXPORTER_CLIENT}"]
