server:
  http_listen_port: 9080
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: "numundo"

scrape_configs:
  # Scrape caddy logs from local path
  - job_name: caddy_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: caddy
          __path__: /var/log/caddy/*.log

  # Scrape Docker containers
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        # filters:
        #   - name: label
        #     values: ["promtail"]
    # Pipeline stages to parse Docker log fields
    pipeline_stages:
      - docker:
          cri: false

    # IMPORTANT: Provide at least one label (e.g., job="docker") for all streams
    relabel_configs:
      - target_label: job
        replacement: docker
      # Optional: also add the container name as a label
      - source_labels: [__meta_docker_container_name]
        target_label: container
